// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGhIgCQu1GQSwQIklC0B_v9dGFX_lFl7U',
    appId: '1:880323948622:web:3a3421c894033f60a1131f',
    messagingSenderId: '880323948622',
    projectId: 'ben-qiaw',
    authDomain: 'ben-qiaw.firebaseapp.com',
    storageBucket: 'ben-qiaw.appspot.com',
    measurementId: 'G-9NN4NEQN3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNIBkQSRe7faEpck4Kxz7dSQLdNXfTKo',
    appId: '1:880323948622:android:acf8d5d0a81071ffa1131f',
    messagingSenderId: '880323948622',
    projectId: 'ben-qiaw',
    storageBucket: 'ben-qiaw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKIW0J-SLFq1WRItRojF1x-zP2ddUMiGc',
    appId: '1:880323948622:ios:6a0b5893ac905eb4a1131f',
    messagingSenderId: '880323948622',
    projectId: 'ben-qiaw',
    storageBucket: 'ben-qiaw.appspot.com',
    iosClientId: '880323948622-hs7rgbfmoihl662993jtu9798khq11l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hunger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKIW0J-SLFq1WRItRojF1x-zP2ddUMiGc',
    appId: '1:880323948622:ios:6a0b5893ac905eb4a1131f',
    messagingSenderId: '880323948622',
    projectId: 'ben-qiaw',
    storageBucket: 'ben-qiaw.appspot.com',
    iosClientId: '880323948622-hs7rgbfmoihl662993jtu9798khq11l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hunger',
  );
}
